#!/bin/bash
# documentpages, counts document pages in a LibreOffice document.
# Created: 2013-04-01
# Based on http://ask.libreoffice.org/en/question/13/how-do-i-get-document-information-from-the-command/?answer=131#post-id-131
# uses: unzip, head and xmlstarlet, from http://xmlstar.sourceforge.net/
#
#
# Copyright 2013 Miguel Mendes Ruiz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ ! -e $1 ] || [[ "$1" == "" ]]; then
  echo "Usage: `basename $01` <filename>"
  exit 1
fi

if [ -e "content.xml" ]; then
  echo "Sorry, this cannot be done because some 'content.xml' already exists"
else
  # extract 'content.xml' from the inputfile
  unzip -qo $1 content.xml

  i=1;
  lastPage="";
  for f in `xmlstarlet el content.xml`;
  do
    n=${f/*:}
    if [[ "$n" =~ "page-number" ]]; then
      w=`xmlstarlet sel -t -v "$f" content.xml | head -n 1`
      lastPage="$n: $w"
    fi
    if [[ "$n" =~ "page-break" ]]; then
      i+=1;
    fi
  done
  rm content.xml
  echo "last-$lastPage"
  echo "page-breaks-count: $i"
fi
